import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import WhatsLogo from "./assets/whats-logo.png";
import { CartProvider } from "./componets/cart-context";
import Navbar from "./componets/menu";
import { CartDrawerProvider } from "./componets/cart-drawer-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="ptBR">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <CartProvider>
//           <CartDrawerProvider>
//             <Navbar />
//             <div className="mt-14">{children}</div>
//           </CartDrawerProvider>
//         </CartProvider>

//         <a
//           href="https://wa.me/5541996301244?text=Olá!%20Gostaria%20de%20saber%20mais%20sobre%20os%20produtos%20de%20limpeza%20disponíveis%20na%20loja."
//           target="_blank"
//           rel="noopener noreferrer"
//           className="group fixed bottom-1.5 right-1.5 bg-green-500 text-white p-1 rounded-full shadow-lg flex items-center justify-center transition-all duration-300 hover:bg-green-600 z-50"
//           style={{
//             fontSize: "24px",
//           }}
//         >
//           <Image
//             src={WhatsLogo}
//             alt="WhatsApp"
//             width={48}
//             height={48}
//             className="whatsapp-logo w-12 h-12 transition-all duration-300 group-hover:scale-110"
//           />
//           <span className="whatsapp-text mr-4 hidden group-hover:inline-block ml-3 text-sm">
//             Enviar mensagem
//           </span>
//         </a>

//         <footer className="bg-blue-600 text-white py-6 mt-10 flex justify-end">
//           <div className="text-center text-sm">
//             © {new Date().getFullYear()} Loja de Produtos de Limpeza. Todos os
//             direitos reservados.
//           </div>
//         </footer>
//       </body>
//     </html>
//   );
// }

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ptBR">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <CartProvider>
          <CartDrawerProvider>
            <Navbar />
            <main className="flex-1 mt-14">{children}</main>
          </CartDrawerProvider>
        </CartProvider>

        {/* Botão WhatsApp */}
        <a
          href="https://wa.me/5541996301244?text=Olá!%20Gostaria%20de%20saber%20mais%20sobre%20os%20produtos%20de%20limpeza%20disponíveis%20na%20loja."
          target="_blank"
          rel="noopener noreferrer"
          className="group fixed bottom-1.5 right-1.5 bg-green-500 text-white p-1 rounded-full shadow-lg flex items-center justify-center transition-all duration-300 hover:bg-green-600 z-50"
          style={{
            fontSize: "24px",
          }}
        >
          <Image
            src={WhatsLogo}
            alt="WhatsApp"
            width={48}
            height={48}
            className="whatsapp-logo w-12 h-12 transition-all duration-300 group-hover:scale-110"
          />
          <span className="whatsapp-text mr-4 hidden group-hover:inline-block ml-3 text-sm">
            Enviar mensagem
          </span>
        </a>

        {/* Footer fixo no fim da página */}
        <footer className="bg-blue-600 text-white py-6 flex justify-end">
          <div className="text-center text-sm w-full">
            © {new Date().getFullYear()} Loja de Produtos de Limpeza - Bigus.
            Todos os direitos reservados.
          </div>
        </footer>
      </body>
    </html>
  );
}
